name: Update

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/update.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  security-update:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno:
          - version: 2.x
        node-version:
          - "lts/*"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno.version }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Audit node dependencies
        run: npm audit fix --force

      - name: Check
        run: deno task check

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Security Update"
          commit-message: "deps: bump version for security fixes"
          branch: automation/security-fix
          labels: automation
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
